### PR TITLE
Allow angular 12 and 13 as peer dependency

### PR DESCRIPTION
**Pull request by martin31821**
Updated the peer dependencies to include angular 12 and 13. I'm using it in an application with angular 13 and it works nicely.

Also, I changed the rxJS versions to 6 || 7 || 8, because these are versioned independently of angular itself.

### CODE REVIEW

**Review by smoke — APPROVED** [review]

**Comment by martin31821** [comment]
Could you also release a new version to use?

**Comment by smoke** [comment]
@martin31821 Thank you for the PR! 
It took a bit of time to update the demo to Angular 12 as well the package dependencies.
Please find the new package version here https://www.npmjs.com/package/ngx-api-utils/v/1.0.11 

I hope it works well for you! 
I recently got stuck on older Angular versions and lost track of new goodies, so can't test it well.
Let me know in case of issues - will be happy to help :)

**Comment by smoke** [comment]
@martin31821 on a side note - I am curious in what kind of project do you use this package, so I would appreciate it if you can share any kind of information about it that you feel comfortable :)

**Comment by martin31821** [comment]
Right now it's in an evaluation stage, and as it looks quite promising I'm planning to use it for a few projects of mine, one is electron based to authenticate against a data distribution server (professional audio) and two web based projects (medical area)

**Comment by smoke** [comment]
@martin31821 thank you for sharing! Let me know if you have some questions / struggles - I will be happy to help.

**Pull request merged**
